package com.example.mapamundi

data class GameUIState(
    val pregunta: String = "",
    val respuesta: String = "",
    val gameOver: Boolean = false,
    val aciertos: Int = 0
)

var paisesTodos: MutableList<GameUIState> = mutableListOf(
    GameUIState("AUSTRALIA", "CAMBERRA"),
    GameUIState("NUEVA ZELANDA", "WELLINGTON"),
    GameUIState("PAPUA NUEVA GUINEA", "PORT MORESBY"),
    GameUIState("FIYI", "SUVA"),
    GameUIState("ISLAS MARSHALL", "MAJURO"),
    GameUIState("ISLAS SALOMON", "HONIARA"),
    GameUIState("KIRIBATI", "TARAWA SUR"),
    GameUIState("TONGA", "NUKUALOFA"),
    GameUIState("SAMOA", "APIA"),
    GameUIState("TUVALU", "FUNAFUTI"),
    GameUIState("VANUATU", "PORT VILA"),
    GameUIState("MICRONESIA", "PALIKIR"),
    GameUIState("NAURU", "YAREN"),
    GameUIState("PALAOS", "NGERULMUD"),
    GameUIState("AFGANISTAN", "KABUL"),
    GameUIState("ARABIA SAUDI", "RIAD"),
    GameUIState("ARMENIA", "EREVAN"),
    GameUIState("AZERBAYAN", "BAKU"),
    GameUIState("BANGLADESH", "DACA"),
    GameUIState("BAHREIN", "MANAMA"),
    GameUIState("BIRMANIA", "NAIPYIDO"),
    GameUIState("BRUNEI", "BANDAR SERI BEGAWAN"),
    GameUIState("BUTAN", "TIMBU"),
    GameUIState("CAMBOYA", "NOM PEN"),
    GameUIState("QATAR", "DOHA"),
    GameUIState("CHINA", "PEKIN"),
    GameUIState("CHIPRE", "NICOSIA"),
    GameUIState("COREA DEL NORTE", "PIONYANG"),
    GameUIState("COREA DEL SUR", "SEUL"),
    GameUIState("EMIRATOS ARABES UNIDOS", "ABU DABI"),
    GameUIState("FILIPINAS", "MANILA"),
    GameUIState("GEORGIA", "TFLIS"),
    GameUIState("INDIA", "NUEVA DELHI"),
    GameUIState("INDONESIA", "YAKARTA"),
    GameUIState("IRAK", "BAGDAD"),
    GameUIState("IRAN", "TEHERAN"),
    GameUIState("ISRAEL", "JERUSALEN"),
    GameUIState("JAPON", "TOKIO"),
    GameUIState("JORDANIA", "AMAN"),
    GameUIState("KAZAJISTAN", "ASTANA"),
    GameUIState("KIRGUISTAN", "BISKEK"),
    GameUIState("KUWAIT", "KUWAIT"),
    GameUIState("LAOS", "VIENTIAN"),
    GameUIState("LIBANO", "BEIRUT"),
    GameUIState("MALDIVAS", "MALE"),
    GameUIState("MALASIA", "KUALA LUMPUR"),
    GameUIState("MONGOLIA", "ULAN BATOR"),
    GameUIState("NEPAL", "KATMANDU"),
    GameUIState("OMAN", "MASCATE"),
    GameUIState("PAKISTAN", "ISLAMABAD"),
    GameUIState("SINGAPUR", "SINGAPUR"),
    GameUIState("SIRIA", "DAMASCO"),
    GameUIState("SRI LANKA", "SRI JAYAWARDENAPURA KOTTE"),
    GameUIState("TAYIKISTAN", "DUSAMBE"),
    GameUIState("TAILANDIA", "BANGKOK"),
    GameUIState("TIMOR ORIENTAL", "DILI"),
    GameUIState("TURQUIA", "ANKARA"),
    GameUIState("TURKMENISTAN", "ASJABAD"),
    GameUIState("UZBEKISTAN", "TASKENT"),
    GameUIState("VIETNAM", "HANOI"),
    GameUIState("YEMEN", "SANA"),
    GameUIState("CANADA", "OTTAWA"),
    GameUIState("ESTADOS UNIDOS", "WASHINGTON"),
    GameUIState("MEXICO", "CIUDAD DE MEXICO"),
    GameUIState("BELICE", "BELMOPAN"),
    GameUIState("COSTA RICA", "SAN JOSE"),
    GameUIState("EL SALVADOR", "SAN SALVADOR"),
    GameUIState("GUATEMALA", "CIUDAD DE GUATEMALA"),
    GameUIState("NICARAGUA", "MANAGUA"),
    GameUIState("ARGENTINA", "BUENOS AIRES"),
    GameUIState("BOLIVIA", "SUCRE"),
    GameUIState("BRASIL", "BRASILIA"),
    GameUIState("CHILE", "SANTIAGO DE CHILE"),
    GameUIState("COLOMBIA", "BOGOTA"),
    GameUIState("ECUADOR", "QUITO"),
    GameUIState("PARAGUAY", "ASUNCION"),
    GameUIState("PERU", "LIMA"),
    GameUIState("SURINAM", "PARABARIMO"),
    GameUIState("TRINIDAD Y TOBAGO", "PUERTO ESPAÑA"),
    GameUIState("URUGUAY", "MONTEVIDEO"),
    GameUIState("VENEZUELA", "CARACAS"),
    GameUIState("ANTIGUA Y BARBUDA", "SAINT JOHN"),
    GameUIState("BAHAMAS", "NASAU"),
    GameUIState("BARBADOS", "BRIDGETOWN"),
    GameUIState("CUBA", "LA HABANA"),
    GameUIState("DOMINICA", "ROSEAU"),
    GameUIState("GRANADA", "SAINT GEORGE"),
    GameUIState("GUYANA", "GEORGETOWN"),
    GameUIState("HAITI", "PUERTO PRINCIPE"),
    GameUIState("JAMAICA", "KINGSTON"),
    GameUIState("REPUBLICA DOMINICANA", "SANTO DOMINGO"),
    GameUIState("SAN CRISTOBAL Y NIEVES", "BASSETERRE"),
    GameUIState("SAN VICENTE Y LAS GRANADINAS", "KINGSTOWN"),
    GameUIState("SANTA LUCIA", "CASTRIES"),
    GameUIState("RUSIA", "MOSCU"),
    GameUIState("ALEMANIA", "BERLIN"),
    GameUIState("REINO UNIDO", "LONDRES"),
    GameUIState("FRANCIA", "PARIS"),
    GameUIState("ITALIA", "ROMA"),
    GameUIState("ESPAÑA", "MADRID"),
    GameUIState("UCRANIA", "KIEV"),
    GameUIState("POLONIA", "VARSOVIA"),
    GameUIState("RUMANIA", "BUCAREST"),
    GameUIState("PAISES BAJOS", "AMSTERDAM"),
    GameUIState("BELGICA", "BRUSELAS"),
    GameUIState("REPUBLICA CHECA", "PRAGA"),
    GameUIState("SUECIA", "ESTOCOLMO"),
    GameUIState("GRECIA", "ATENAS"),
    GameUIState("PORTUGAL", "LISBOA"),
    GameUIState("HUNGRIA", "BUDAPEST"),
    GameUIState("BIELORRUSIA", "MINSK"),
    GameUIState("AUSTRIA", "VIENA"),
    GameUIState("SUIZA", "BERNA"),
    GameUIState("SERBIA", "BELGRADO"),
    GameUIState("BULGARIA", "SOFIA"),
    GameUIState("DINAMARCA", "COPENHAGUE"),
    GameUIState("FINLANDIA", "HELSINKI"),
    GameUIState("NORUEGA", "OSLO"),
    GameUIState("ESLOVAQUIA", "BRATISLAVA"),
    GameUIState("IRLANDA", "DUBLIN"),
    GameUIState("CROACIA", "ZAGREB"),
    GameUIState("MOLDAVIA", "CHISINAU"),
    GameUIState("BOSNIA", "SARAJEVO"),
    GameUIState("ALBANIA", "TIRANA"),
    GameUIState("LITUANIA", "VILNIUS"),
    GameUIState("MACEDONIA", "SKOPJE"),
    GameUIState("ESLOVENIA", "LIUBLIANA"),
    GameUIState("LETONIA", "RIGA"),
    GameUIState("ESTONIA", "TALLIN"),
    GameUIState("MONTENEGRO", "PODGORICA"),
    GameUIState("LUXEMBURGO", "LUXEMBURGO"),
    GameUIState("MALTA", "LA VALLETA"),
    GameUIState("ISLANDIA", "REIKIAVIK"),
    GameUIState("ANDORRA", "ANDORRA LA VELLA"),
    GameUIState("LIECHTENSTEIN", "VADUZ"),
    GameUIState("MONACO", "MONACO"),
    GameUIState("SAN MARINO", "SAN MARINO"),
    GameUIState("CIUDAD DEL VATICANO", "CIUDAD DEL VATICANO"),
    GameUIState("ANGOLA", "LUANDA"),
    GameUIState("ARGELIA", "ARGEL"),
    GameUIState("BENIN", "PORTO NOVO"),
    GameUIState("BOTSUANA", "GABORONE"),
    GameUIState("BURKINA FASO", "UAGADUGU"),
    GameUIState("BURUNDI", "BUYUMBURA"),
    GameUIState("CABO VERDE", "PRAIA"),
    GameUIState("CAMERUN", "YAUNDE"),
    GameUIState("REPUBLICA CENTROAFRICANA", "BANGUI"),
    GameUIState("COMORES", "MORONI"),
    GameUIState("COSTA DE MARFIL", "YAMUSUKRO"),
    GameUIState("CHAD", "YAMENA"),
    GameUIState("EGIPTO", "EL CAIRO"),
    GameUIState("ERITREA", "ASMARA"),
    GameUIState("ETIOPIA", "ADDIS ABEBA"),
    GameUIState("GABON", "LIBRE VILLE"),
    GameUIState("GAMBIA", "BANJUL"),
    GameUIState("GHANA", "ACCRA"),
    GameUIState("GUINEA CONAKRY", "CONAKRY"),
    GameUIState("GUINEA BISSAU", "BISSAU"),
    GameUIState("GUINEA ECUATORIAL", "MALABO"),
    GameUIState("KENIA", "NAIROBI"),
    GameUIState("LESOTO", "MASERU"),
    GameUIState("LIBERIA", "MONROVIA"),
    GameUIState("LIBIA", "TRIPOLI"),
    GameUIState("MADAGASCAR", "ANTANANARIVO"),
    GameUIState("MALAUI", "LILONGUE"),
    GameUIState("MALI", "BAMAKO"),
    GameUIState("MARRUECOS", "RABAT"),
    GameUIState("MAURICIO", "PORT LOUIS"),
    GameUIState("MAURITANIA", "NUAKCHOT"),
    GameUIState("MOZAMBIQUE", "MAPUTO"),
    GameUIState("NAMIBIA", "WINDHOEK"),
    GameUIState("NIGER", "NIAMEY"),
    GameUIState("NIGERIA", "ABUYA"),
    GameUIState("RUANDA", "KIGALI"),
    GameUIState("REPUBLICA DEL CONGO", "BRAZZAVILLE"),
    GameUIState("REPUBLICA DEMOCRATICA DEL CONGO", "KINSHASA"),
    GameUIState("SANTO TOME Y PRINCIPE", "SANTO TOME"),
    GameUIState("SENEGAL", "DAKAR"),
    GameUIState("SEYCHELLES", "VICTORIA"),
    GameUIState("SIERRA LEONA", "FREETOWN"),
    GameUIState("SOMALIA", "MOGADISCIO"),
    GameUIState("SUDAFRICA", "PRETORIA"),
    GameUIState("SUDAN", "JARTUM"),
    GameUIState("SUDAN DEL SUR", "YUBA"),
    GameUIState("SUAZILANDIA", "LOBAMBA"),
    GameUIState("TANZANIA", "DAR EL SALAM"),
    GameUIState("TUNEZ", "TUNEZ"),
    GameUIState("TOGO", "LOME"),
    GameUIState("UGANDA", "KAMPALA"),
    GameUIState("YIBUTI", "YIBUTI"),
    GameUIState("ZAMBIA", "LUSAKA"),
    GameUIState("ZIMBABUE", "HARE")
)
var paisesTodosReversed: MutableList<GameUIState> = mutableListOf(
    GameUIState("CAMBERRA", "AUSTRALIA"),
    GameUIState("WELLINGTON", "NUEVA ZELANDA"),
    GameUIState("PORT MORESBY", "PAPUA NUEVA GUINEA"),
    GameUIState("SUVA", "FIYI"),
    GameUIState("MAJURO", "ISLAS MARSHALL"),
    GameUIState("HONIARA", "ISLAS SALOMON"),
    GameUIState("TARAWA SUR", "KIRIBATI"),
    GameUIState("NUKUALOFA", "TONGA"),
    GameUIState("APIA", "SAMOA"),
    GameUIState("FUNAFUTI", "TUVALU"),
    GameUIState("PORT VILA", "VANUATU"),
    GameUIState("PALIKIR", "MICRONESIA"),
    GameUIState("YAREN", "NAURU"),
    GameUIState("NGERULMUD", "PALAOS"),
    GameUIState("KABUL", "AFGANISTAN"),
    GameUIState("RIAD", "ARABIA SAUDI"),
    GameUIState("EREVAN", "ARMENIA"),
    GameUIState("BAKU", "AZERBAYAN"),
    GameUIState("DACA", "BANGLADESH"),
    GameUIState("MANAMA", "BAHREIN"),
    GameUIState("NAIPYIDO", "BIRMANIA"),
    GameUIState("BANDAR SERI BEGAWAN", "BRUNEI"),
    GameUIState("BUTAN", "BUTAN"),
    GameUIState("NOM PEN", "CAMBOYA"),
    GameUIState("DOHA", "QATAR"),
    GameUIState("PEKIN", "CHINA"),
    GameUIState("NICOSIA", "CHIPRE"),
    GameUIState("PIONYANG", "COREA DEL NORTE"),
    GameUIState("SEUL", "COREA DEL SUR"),
    GameUIState("ABU DABI", "EMIRATOS ARABES UNIDOS"),
    GameUIState("MANILA", "FILIPINAS"),
    GameUIState("TFLIS", "GEORGIA"),
    GameUIState("NUEVA DELHI", "INDIA"),
    GameUIState("YAKARTA", "INDONESIA"),
    GameUIState("BAGDAD", "IRAK"),
    GameUIState("TEHERAN", "IRAN"),
    GameUIState("JERUSALEN", "ISRAEL"),
    GameUIState("TOKIO", "JAPON"),
    GameUIState("AMAN", "JORDANIA"),
    GameUIState("ASTANA", "KAZAJISTAN"),
    GameUIState("BISKEK", "KIRGUISTAN"),
    GameUIState("KUWAIT", "KUWAIT"),
    GameUIState("VIENTIAN", "LAOS"),
    GameUIState("BEIRUT", "LIBANO"),
    GameUIState("MALE", "MALDIVAS"),
    GameUIState("KUALA LUMPUR", "MALASIA"),
    GameUIState("ULAN BATOR", "MONGOLIA"),
    GameUIState("KATMANDU", "NEPAL"),
    GameUIState("MASCATE", "OMAN"),
    GameUIState("ISLAMABAD", "PAKISTAN"),
    GameUIState("SINGAPUR", "SINGAPUR"),
    GameUIState("DAMASCO", "SIRIA"),
    GameUIState("SRI JAYAWARDENAPURA KOTTE", "SRI LANKA"),
    GameUIState("DUSAMBE", "TAYIKISTAN"),
    GameUIState("BANGKOK", "TAILANDIA"),
    GameUIState("DILI", "TIMOR ORIENTAL"),
    GameUIState("ANKARA", "TURQUIA"),
    GameUIState("ASJABAD", "TURKMENISTAN"),
    GameUIState("TAKENT", "UZBEKISTAN"),
    GameUIState("HANOI", "VIETNAM"),
    GameUIState("SANA", "YEMEN"),
    GameUIState("OTTAWA", "CANADA"),
    GameUIState("WASHINGTON", "ESTADOS UNIDOS"),
    GameUIState("CIUDAD DE MEXICO", "MEXICO"),
    GameUIState("BELMOPAN", "BELICE"),
    GameUIState("SAN JOSE", "COSTA RICA"),
    GameUIState("SAN SALVADOR", "EL SALVADOR"),
    GameUIState("CIUDAD DE GUATEMALA", "GUATEMALA"),
    GameUIState("MANAGUA", "NICARAGUA"),
    GameUIState("BUENOS AIRES", "ARGENTINA"),
    GameUIState("SUCRE", "BOLIVIA"),
    GameUIState("BRASILIA", "BRASIL"),
    GameUIState("SANTIAGO DE CHILE", "CHILE"),
    GameUIState("BOGOTA", "COLOMBIA"),
    GameUIState("QUITO", "ECUADOR"),
    GameUIState("ASUNCION", "PARAGUAY"),
    GameUIState("LIMA", "PERU"),
    GameUIState("PARABARIMO", "SURINAM"),
    GameUIState("PUERTO ESPAÑA", "TRINIDAD Y TOBAGO"),
    GameUIState("MONTEVIDEO", "URUGUAY"),
    GameUIState("CARACAS", "VENEZUELA"),
    GameUIState("SAINT JOHN", "ANTIGUA Y BARBUDA"),
    GameUIState("NASAU", "BAHAMAS"),
    GameUIState("BRIDGETOWN", "BARBADOS"),
    GameUIState("LA HABANA", "CUBA"),
    GameUIState("ROSEAU", "DOMINICA"),
    GameUIState("SAINT GEORGE", "GRANADA"),
    GameUIState("GEORGETOWN", "GUYANA"),
    GameUIState("PUERTO PRINCIPE", "HAITI"),
    GameUIState("KINGSTON", "JAMAICA"),
    GameUIState("SANTO DOMINGO", "REPUBLICA DOMINICANA"),
    GameUIState("BASSETERRE", "SAN CRISTOBAL Y NIEVES"),
    GameUIState("KINGSTOWN", "SAN VICENTE Y LAS GRANADINAS"),
    GameUIState("CASTRIES", "SANTA LUCIA"),
    GameUIState("MOSCU", "RUSIA"),
    GameUIState("BERLIN", "ALEMANIA"),
    GameUIState("LONDRES", "REINO UNIDO"),
    GameUIState("PARIS", "FRANCIA"),
    GameUIState("ROMA", "ITALIA"),
    GameUIState("MADRID", "ESPAÑA"),
    GameUIState("KIEV", "UCRANIA"),
    GameUIState("VARSOVIA", "POLONIA"),
    GameUIState("BUCAREST", "RUMANIA"),
    GameUIState("AMSTERDAM", "PAISES BAJOS"),
    GameUIState("BRUSELAS", "BELGICA"),
    GameUIState("PRAGA", "REPUBLICA CHECA"),
    GameUIState("ESTOCOLMO", "SUECIA"),
    GameUIState("ATENAS", "GRECIA"),
    GameUIState("LISBOA", "PORTUGAL"),
    GameUIState("BUDAPEST", "HUNGRIA"),
    GameUIState("MINSK", "BIELORRUSIA"),
    GameUIState("VIENA", "AUSTRIA"),
    GameUIState("BERNA", "SUIZA"),
    GameUIState("BELGRADO", "SERBIA"),
    GameUIState("SOFIA", "BULGARIA"),
    GameUIState("COPENHAGUE", "DINAMARCA"),
    GameUIState("HELSINKI", "FINLANDIA"),
    GameUIState("OSLO", "NORUEGA"),
    GameUIState("BRATISLAVA", "ESLOVAQUIA"),
    GameUIState("DUBLIN", "IRLANDA"),
    GameUIState("ZAGREB", "CROACIA"),
    GameUIState("CHISINAU", "MOLDAVIA"),
    GameUIState("SARAJEVO", "BOSNIA"),
    GameUIState("TIRANA", "ALBANIA"),
    GameUIState("VILNIUS", "LITUANIA"),
    GameUIState("SKOPJE", "MACEDONIA"),
    GameUIState("LIUBLIANA", "ESLOVENIA"),
    GameUIState("RIGA", "LETONIA"),
    GameUIState("TALLIN", "ESTONIA"),
    GameUIState("PODGORICA", "MONTENEGRO"),
    GameUIState("LUXEMBURGO", "LUXEMBURGO"),
    GameUIState("LA VALLETA", "MALTA"),
    GameUIState("REIKIAVIK", "ISLANDIA"),
    GameUIState("ANDORRA LA VELLA", "ANDORRA"),
    GameUIState("VADUZ", "LIECHTENSTEIN"),
    GameUIState("MONACO", "MONACO"),
    GameUIState("SAN MARINO", "SAN MARINO"),
    GameUIState("CIUDAD DEL VATICANO", "CIUDAD DEL VATICANO"),
    GameUIState("LUANDA", "ANGOLA"),
    GameUIState("ARGEL", "ARGELIA"),
    GameUIState("PORTO NOVO", "BENIN"),
    GameUIState("GABORONE", "BOTSUANA"),
    GameUIState("UAGADUGU", "BURKINA FASO"),
    GameUIState("BUYUMBURA", "BURUNDI"),
    GameUIState("PRAIA", "CABO VERDE"),
    GameUIState("YAUNDE", "CAMERUN"),
    GameUIState("BANGUI", "REPUBLICA CENTROAFRICANA"),
    GameUIState("MORONI", "COMORES"),
    GameUIState("YAMUSUKRO", "COSTA DE MARFIL"),
    GameUIState("YAMENA", "CHAD"),
    GameUIState("EL CAIRO", "EGIPTO"),
    GameUIState("ASMARA", "ERITREA"),
    GameUIState("ADDIS ABEBA", "ETIOPIA"),
    GameUIState("LIBRE VILLE", "GABON"),
    GameUIState("BANJUL", "GAMBIA"),
    GameUIState("ACCRA", "GHANA"),
    GameUIState("CONAKRY", "GUINEA CONAKRY"),
    GameUIState("BISSAU", "GUINEA BISSAU"),
    GameUIState("MALABO", "GUINEA ECUATORIAL"),
    GameUIState("NAIROBI", "KENIA"),
    GameUIState("MASERU", "LESOTO"),
    GameUIState("MONROVIA", "LIBERIA"),
    GameUIState("TRIPOLI", "LIBIA"),
    GameUIState("ANTANANARIVO", "MADAGASCAR"),
    GameUIState("LILONGUE", "MALAUI"),
    GameUIState("BAMAKO", "MALI"),
    GameUIState("RABAT", "MARRUECOS"),
    GameUIState("PORT LOUIS", "MAURICIO"),
    GameUIState("NUAKCHOT", "MAURITANIA"),
    GameUIState("MAPUTO", "MOZAMBIQUE"),
    GameUIState("WINDHOEK", "NAMIBIA"),
    GameUIState("NIAMEY", "NIGER"),
    GameUIState("ABUYA", "NIGERIA"),
    GameUIState("KIGALI", "RUANDA"),
    GameUIState("BRAZZAVILLE", "REPUBLICA DEL CONGO"),
    GameUIState("KINSHASA", "REPUBLICA DEMOCRATICA DEL CONGO"),
    GameUIState("SANTO TOME", "SANTO TOME Y PRINCIPE"),
    GameUIState("DAKAR", "SENEGAL"),
    GameUIState("VICTORIA", "SEYCHELLES"),
    GameUIState("FREETOWN", "SIERRA LEONA"),
    GameUIState("MOGADISCIO", "SOMALIA"),
    GameUIState("PRETORIA", "SUDAFRICA"),
    GameUIState("JARTUM", "SUDAN"),
    GameUIState("YUBA", "SUDAN DEL SUR"),
    GameUIState("LOBAMBA", "SUAZILANDIA"),
    GameUIState("DAR EL SALAM", "TANZANIA"),
    GameUIState("TUNEZ", "TUNEZ"),
    GameUIState("LOME", "TOGO"),
    GameUIState("KAMPALA", "UGANDA"),
    GameUIState("YIBUTI", "YIBUTI"),
    GameUIState("LUSAKA", "ZAMBIA"),
    GameUIState("HARE", "ZIMBABUE")
)
var paisesOceania: MutableList<GameUIState> = mutableListOf(
    GameUIState("AUSTRALIA", "CAMBERRA"),
    GameUIState("NUEVA ZELANDA", "WELLINGTON"),
    GameUIState("PAPUA NUEVA GUINEA", "PORT MORESBY"),
    GameUIState("FIYI", "SUVA"),
    GameUIState("ISLAS MARSHALL", "MAJURO"),
    GameUIState("ISLAS SALOMON", "HONIARA"),
    GameUIState("KIRIBATI", "TARAWA SUR"),
    GameUIState("TONGA", "NUKUALOFA"),
    GameUIState("SAMOA", "APIA"),
    GameUIState("TUVALU", "FUNAFUTI"),
    GameUIState("VANUATU", "PORT VILA"),
    GameUIState("MICRONESIA", "PALIKIR"),
    GameUIState("NAURU", "YAREN"),
    GameUIState("PALAOS", "NGERULMUD")
)
var paisesOceaniaReversed: MutableList<GameUIState> = mutableListOf(
    GameUIState("CAMBERRA", "AUSTRALIA"),
    GameUIState("WELLINGTON", "NUEVA ZELANDA"),
    GameUIState("PORT MORESBY", "PAPUA NUEVA GUINEA"),
    GameUIState("SUVA", "FIYI"),
    GameUIState("MAJURO", "ISLAS MARSHALL"),
    GameUIState("HONIARA", "ISLAS SALOMON"),
    GameUIState("TARAWA SUR", "KIRIBATI"),
    GameUIState("NUKUALOFA", "TONGA"),
    GameUIState("APIA", "SAMOA"),
    GameUIState("FUNAFUTI", "TUVALU"),
    GameUIState("PORT VILA", "VANUATU"),
    GameUIState("PALIKIR", "MICRONESIA"),
    GameUIState("YAREN", "NAURU"),
    GameUIState("NGERULMUD", "PALAOS")
)
var paisesAsia: MutableList<GameUIState> = mutableListOf(
    GameUIState("AFGANISTAN", "KABUL"),
    GameUIState("ARABIA SAUDI", "RIAD"),
    GameUIState("ARMENIA", "EREVAN"),
    GameUIState("AZERBAYAN", "BAKU"),
    GameUIState("BANGLADESH", "DACA"),
    GameUIState("BAHREIN", "MANAMA"),
    GameUIState("BIRMANIA", "NAIPYIDO"),
    GameUIState("BRUNEI", "BANDAR SERI BEGAWAN"),
    GameUIState("BUTAN", "TIMBU"),
    GameUIState("CAMBOYA", "NOM PEN"),
    GameUIState("QATAR", "DOHA"),
    GameUIState("CHINA", "PEKIN"),
    GameUIState("CHIPRE", "NICOSIA"),
    GameUIState("COREA DEL NORTE", "PIONYANG"),
    GameUIState("COREA DEL SUR", "SEUL"),
    GameUIState("EMIRATOS ARABES UNIDOS", "ABU DABI"),
    GameUIState("FILIPINAS", "MANILA"),
    GameUIState("GEORGIA", "TFLIS"),
    GameUIState("INDIA", "NUEVA DELHI"),
    GameUIState("INDONESIA", "YAKARTA"),
    GameUIState("IRAK", "BAGDAD"),
    GameUIState("IRAN", "TEHERAN"),
    GameUIState("ISRAEL", "JERUSALEN"),
    GameUIState("JAPON", "TOKIO"),
    GameUIState("JORDANIA", "AMAN"),
    GameUIState("KAZAJISTAN", "ASTANA"),
    GameUIState("KIRGUISTAN", "BISKEK"),
    GameUIState("KUWAIT", "KUWAIT"),
    GameUIState("LAOS", "VIENTIAN"),
    GameUIState("LIBANO", "BEIRUT"),
    GameUIState("MALDIVAS", "MALE"),
    GameUIState("MALASIA", "KUALA LUMPUR"),
    GameUIState("MONGOLIA", "ULAN BATOR"),
    GameUIState("NEPAL", "KATMANDU"),
    GameUIState("OMAN", "MASCATE"),
    GameUIState("PAKISTAN", "ISLAMABAD"),
    GameUIState("SINGAPUR", "SINGAPUR"),
    GameUIState("SIRIA", "DAMASCO"),
    GameUIState("SRI LANKA", "SRI JAYAWARDENAPURA KOTTE"),
    GameUIState("TAYIKISTAN", "DUSAMBE"),
    GameUIState("TAILANDIA", "BANGKOK"),
    GameUIState("TIMOR ORIENTAL", "DILI"),
    GameUIState("TURQUIA", "ANKARA"),
    GameUIState("TURKMENISTAN", "ASJABAD"),
    GameUIState("UZBEKISTAN", "TASKENT"),
    GameUIState("VIETNAM", "HANOI"),
    GameUIState("YEMEN", "SANA")
)
var paisesAsiaReversed: MutableList<GameUIState> = mutableListOf(
    GameUIState("KABUL", "AFGANISTAN"),
    GameUIState("RIAD", "ARABIA SAUDI"),
    GameUIState("EREVAN", "ARMENIA"),
    GameUIState("BAKU", "AZERBAYAN"),
    GameUIState("DACA", "BANGLADESH"),
    GameUIState("MANAMA", "BAHREIN"),
    GameUIState("NAIPYIDO", "BIRMANIA"),
    GameUIState("BANDAR SERI BEGAWAN", "BRUNEI"),
    GameUIState("BUTAN", "BUTAN"),
    GameUIState("NOM PEN", "CAMBOYA"),
    GameUIState("DOHA", "QATAR"),
    GameUIState("PEKIN", "CHINA"),
    GameUIState("NICOSIA", "CHIPRE"),
    GameUIState("PIONYANG", "COREA DEL NORTE"),
    GameUIState("SEUL", "COREA DEL SUR"),
    GameUIState("ABU DABI", "EMIRATOS ARABES UNIDOS"),
    GameUIState("MANILA", "FILIPINAS"),
    GameUIState("TFLIS", "GEORGIA"),
    GameUIState("NUEVA DELHI", "INDIA"),
    GameUIState("YAKARTA", "INDONESIA"),
    GameUIState("BAGDAD", "IRAK"),
    GameUIState("TEHERAN", "IRAN"),
    GameUIState("JERUSALEN", "ISRAEL"),
    GameUIState("TOKIO", "JAPON"),
    GameUIState("AMAN", "JORDANIA"),
    GameUIState("ASTANA", "KAZAJISTAN"),
    GameUIState("BISKEK", "KIRGUISTAN"),
    GameUIState("KUWAIT", "KUWAIT"),
    GameUIState("VIENTIAN", "LAOS"),
    GameUIState("BEIRUT", "LIBANO"),
    GameUIState("MALE", "MALDIVAS"),
    GameUIState("KUALA LUMPUR", "MALASIA"),
    GameUIState("ULAN BATOR", "MONGOLIA"),
    GameUIState("KATMANDU", "NEPAL"),
    GameUIState("MASCATE", "OMAN"),
    GameUIState("ISLAMABAD", "PAKISTAN"),
    GameUIState("SINGAPUR", "SINGAPUR"),
    GameUIState("DAMASCO", "SIRIA"),
    GameUIState("SRI JAYAWARDENAPURA KOTTE", "SRI LANKA"),
    GameUIState("DUSAMBE", "TAYIKISTAN"),
    GameUIState("BANGKOK", "TAILANDIA"),
    GameUIState("DILI", "TIMOR ORIENTAL"),
    GameUIState("ANKARA", "TURQUIA"),
    GameUIState("ASJABAD", "TURKMENISTAN"),
    GameUIState("TAKENT", "UZBEKISTAN"),
    GameUIState("HANOI", "VIETNAM"),
    GameUIState("SANA", "YEMEN")
)
var paisesAm: MutableList<GameUIState> = mutableListOf(
    GameUIState("CANADA", "OTTAWA"),
    GameUIState("ESTADOS UNIDOS", "WASHINGTON"),
    GameUIState("MEXICO", "CIUDAD DE MEXICO"),
    GameUIState("BELICE", "BELMOPAN"),
    GameUIState("COSTA RICA", "SAN JOSE"),
    GameUIState("EL SALVADOR", "SAN SALVADOR"),
    GameUIState("GUATEMALA", "CIUDAD DE GUATEMALA"),
    GameUIState("NICARAGUA", "MANAGUA"),
    GameUIState("ARGENTINA", "BUENOS AIRES"),
    GameUIState("BOLIVIA", "SUCRE"),
    GameUIState("BRASIL", "BRASILIA"),
    GameUIState("CHILE", "SANTIAGO DE CHILE"),
    GameUIState("COLOMBIA", "BOGOTA"),
    GameUIState("ECUADOR", "QUITO"),
    GameUIState("PARAGUAY", "ASUNCION"),
    GameUIState("PERU", "LIMA"),
    GameUIState("SURINAM", "PARAMARIBO"),
    GameUIState("TRINIDAD Y TOBAGO", "PUERTO ESPAÑA"),
    GameUIState("URUGUAY", "MONTEVIDEO"),
    GameUIState("VENEZUELA", "CARACAS"),
    GameUIState("ANTIGUA Y BARBUDA", "SAINT JOHN"),
    GameUIState("BAHAMAS", "NASAU"),
    GameUIState("BARBADOS", "BRIDGETOWN"),
    GameUIState("CUBA", "LA HABANA"),
    GameUIState("DOMINICA", "ROSEAU"),
    GameUIState("GRANADA", "SAINT GEORGE"),
    GameUIState("GUYANA", "GEORGETOWN"),
    GameUIState("HAITI", "PUERTO PRINCIPE"),
    GameUIState("JAMAICA", "KINGSTON"),
    GameUIState("REPUBLICA DOMINICANA", "SANTO DOMINGO"),
    GameUIState("SAN CRISTOBAL Y NIEVES", "BASSETERRE"),
    GameUIState("SAN VICENTE Y LAS GRANADINAS", "KINGSTOWN"),
    GameUIState("SANTA LUCIA", "CASTRIES")
)
var paisesAmReversed: MutableList<GameUIState> = mutableListOf(
    GameUIState("OTTAWA", "CANADA"),
    GameUIState("WASHINGTON", "ESTADOS UNIDOS"),
    GameUIState("CIUDAD DE MEXICO", "MEXICO"),
    GameUIState("BELMOPAN", "BELICE"),
    GameUIState("SAN JOSE", "COSTA RICA"),
    GameUIState("SAN SALVADOR", "EL SALVADOR"),
    GameUIState("CIUDAD DE GUATEMALA", "GUATEMALA"),
    GameUIState("MANAGUA", "NICARAGUA"),
    GameUIState("BUENOS AIRES", "ARGENTINA"),
    GameUIState("SUCRE", "BOLIVIA"),
    GameUIState("BRASILIA", "BRASIL"),
    GameUIState("SANTIAGO DE CHILE", "CHILE"),
    GameUIState("BOGOTA", "COLOMBIA"),
    GameUIState("QUITO", "ECUADOR"),
    GameUIState("ASUNCION", "PARAGUAY"),
    GameUIState("LIMA", "PERU"),
    GameUIState("PARAMARIBO", "SURINAM"),
    GameUIState("PUERTO ESPAÑA", "TRINIDAD Y TOBAGO"),
    GameUIState("MONTEVIDEO", "URUGUAY"),
    GameUIState("CARACAS", "VENEZUELA"),
    GameUIState("SAINT JOHN", "ANTIGUA Y BARBUDA"),
    GameUIState("NASAU", "BAHAMAS"),
    GameUIState("BRIDGETOWN", "BARBADOS"),
    GameUIState("LA HABANA", "CUBA"),
    GameUIState("ROSEAU", "DOMINICA"),
    GameUIState("SAINT GEORGE", "GRANADA"),
    GameUIState("GEORGETOWN", "GUYANA"),
    GameUIState("PUERTO PRINCIPE", "HAITI"),
    GameUIState("KINGSTON", "JAMAICA"),
    GameUIState("SANTO DOMINGO", "REPUBLICA DOMINICANA"),
    GameUIState("BASSETERRE", "SAN CRISTOBAL Y NIEVES"),
    GameUIState("KINGSTOWN", "SAN VICENTE Y LAS GRANADINAS"),
    GameUIState("CASTRIES", "SANTA LUCIA")
)
var paisesEuReversed: MutableList<GameUIState> = mutableListOf(
    GameUIState("MOSCU", "RUSIA"),
    GameUIState("BERLIN", "ALEMANIA"),
    GameUIState("LONDRES", "REINO UNIDO"),
    GameUIState("PARIS", "FRANCIA"),
    GameUIState("ROMA", "ITALIA"),
    GameUIState("MADRID", "ESPAÑA"),
    GameUIState("KIEV", "UCRANIA"),
    GameUIState("VARSOVIA", "POLONIA"),
    GameUIState("BUCAREST", "RUMANIA"),
    GameUIState("AMSTERDAM", "PAISES BAJOS"),
    GameUIState("BRUSELAS", "BELGICA"),
    GameUIState("PRAGA", "REPUBLICA CHECA"),
    GameUIState("ESTOCOLMO", "SUECIA"),
    GameUIState("ATENAS", "GRECIA"),
    GameUIState("LISBOA", "PORTUGAL"),
    GameUIState("BUDAPEST", "HUNGRIA"),
    GameUIState("MINSK", "BIELORRUSIA"),
    GameUIState("VIENA", "AUSTRIA"),
    GameUIState("BERNA", "SUIZA"),
    GameUIState("BELGRADO", "SERBIA"),
    GameUIState("SOFIA", "BULGARIA"),
    GameUIState("COPENHAGUE", "DINAMARCA"),
    GameUIState("HELSINKI", "FINLANDIA"),
    GameUIState("OSLO", "NORUEGA"),
    GameUIState("BRATISLAVA", "ESLOVAQUIA"),
    GameUIState("DUBLIN", "IRLANDA"),
    GameUIState("ZAGREB", "CROACIA"),
    GameUIState("CHISINAU", "MOLDAVIA"),
    GameUIState("SARAJEVO", "BOSNIA"),
    GameUIState("TIRANA", "ALBANIA"),
    GameUIState("VILNIUS", "LITUANIA"),
    GameUIState("SKOPJE", "MACEDONIA"),
    GameUIState("LIUBLIANA", "ESLOVENIA"),
    GameUIState("RIGA", "LETONIA"),
    GameUIState("TALLIN", "ESTONIA"),
    GameUIState("PODGORICA", "MONTENEGRO"),
    GameUIState("LUXEMBURGO", "LUXEMBURGO"),
    GameUIState("LA VALLETA", "MALTA"),
    GameUIState("REIKIAVIK", "ISLANDIA"),
    GameUIState("ANDORRA LA VELLA", "ANDORRA"),
    GameUIState("VADUZ", "LIECHTENSTEIN"),
    GameUIState("MONACO", "MONACO"),
    GameUIState("SAN MARINO", "SAN MARINO"),
    GameUIState("CIUDAD DEL VATICANO", "CIUDAD DEL VATICANO")
)
var paisesEu: MutableList<GameUIState> = mutableListOf(
    GameUIState("RUSIA", "MOSCU"),
    GameUIState("ALEMANIA", "BERLIN"),
    GameUIState("REINO UNIDO", "LONDRES"),
    GameUIState("FRANCIA", "PARIS"),
    GameUIState("ITALIA", "ROMA"),
    GameUIState("ESPAÑA", "MADRID"),
    GameUIState("UCRANIA", "KIEV"),
    GameUIState("POLONIA", "VARSOVIA"),
    GameUIState("RUMANIA", "BUCAREST"),
    GameUIState("PAISES BAJOS", "AMSTERDAM"),
    GameUIState("BELGICA", "BRUSELAS"),
    GameUIState("REPUBLICA CHECA", "PRAGA"),
    GameUIState("SUECIA", "ESTOCOLMO"),
    GameUIState("GRECIA", "ATENAS"),
    GameUIState("PORTUGAL", "LISBOA"),
    GameUIState("HUNGRIA", "BUDAPEST"),
    GameUIState("BIELORRUSIA", "MINSK"),
    GameUIState("AUSTRIA", "VIENA"),
    GameUIState("SUIZA", "BERNA"),
    GameUIState("SERBIA", "BELGRADO"),
    GameUIState("BULGARIA", "SOFIA"),
    GameUIState("DINAMARCA", "COPENHAGUE"),
    GameUIState("FINLANDIA", "HELSINKI"),
    GameUIState("NORUEGA", "OSLO"),
    GameUIState("ESLOVAQUIA", "BRATISLAVA"),
    GameUIState("IRLANDA", "DUBLIN"),
    GameUIState("CROACIA", "ZAGREB"),
    GameUIState("MOLDAVIA", "CHISINAU"),
    GameUIState("BOSNIA", "SARAJEVO"),
    GameUIState("ALBANIA", "TIRANA"),
    GameUIState("LITUANIA", "VILNIUS"),
    GameUIState("MACEDONIA", "SKOPJE"),
    GameUIState("ESLOVENIA", "LIUBLIANA"),
    GameUIState("LETONIA", "RIGA"),
    GameUIState("ESTONIA", "TALLIN"),
    GameUIState("MONTENEGRO", "PODGORICA"),
    GameUIState("LUXEMBURGO", "LUXEMBURGO"),
    GameUIState("MALTA", "LA VALLETA"),
    GameUIState("ISLANDIA", "REIKIAVIK"),
    GameUIState("ANDORRA", "ANDORRA LA VELLA"),
    GameUIState("LIECHTENSTEIN", "VADUZ"),
    GameUIState("MONACO", "MONACO"),
    GameUIState("SAN MARINO", "SAN MARINO"),
    GameUIState("CIUDAD DEL VATICANO", "CIUDAD DEL VATICANO")
)
var paisesAfr: MutableList<GameUIState> = mutableListOf(
    GameUIState("ANGOLA", "LUANDA"),
    GameUIState("ARGELIA", "ARGEL"),
    GameUIState("BENIN", "PORTO NOVO"),
    GameUIState("BOTSUANA", "GABORONE"),
    GameUIState("BURKINA FASO", "UAGADUGU"),
    GameUIState("BURUNDI", "BUYUMBURA"),
    GameUIState("CABO VERDE", "PRAIA"),
    GameUIState("CAMERUN", "YAUNDE"),
    GameUIState("REPUBLICA CENTROAFRICANA", "BANGUI"),
    GameUIState("COMORES", "MORONI"),
    GameUIState("COSTA DE MARFIL", "YAMUSUKRO"),
    GameUIState("CHAD", "YAMENA"),
    GameUIState("EGIPTO", "EL CAIRO"),
    GameUIState("ERITREA", "ASMARA"),
    GameUIState("ETIOPIA", "ADDIS ABEBA"),
    GameUIState("GABON", "LIBRE VILLE"),
    GameUIState("GAMBIA", "BANJUL"),
    GameUIState("GHANA", "ACCRA"),
    GameUIState("GUINEA CONAKRY", "CONAKRY"),
    GameUIState("GUINEA BISSAU", "BISSAU"),
    GameUIState("GUINEA ECUATORIAL", "MALABO"),
    GameUIState("KENIA", "NAIROBI"),
    GameUIState("LESOTO", "MASERU"),
    GameUIState("LIBERIA", "MONROVIA"),
    GameUIState("LIBIA", "TRIPOLI"),
    GameUIState("MADAGASCAR", "ANTANANARIVO"),
    GameUIState("MALAUI", "LILONGUE"),
    GameUIState("MALI", "BAMAKO"),
    GameUIState("MARRUECOS", "RABAT"),
    GameUIState("MAURICIO", "PORT LOUIS"),
    GameUIState("MAURITANIA", "NUAKCHOT"),
    GameUIState("MOZAMBIQUE", "MAPUTO"),
    GameUIState("NAMIBIA", "WINDHOEK"),
    GameUIState("NIGER", "NIAMEY"),
    GameUIState("NIGERIA", "ABUYA"),
    GameUIState("RUANDA", "KIGALI"),
    GameUIState("REPUBLICA DEL CONGO", "BRAZZAVILLE"),
    GameUIState("REPUBLICA DEMOCRATICA DEL CONGO", "KINSHASA"),
    GameUIState("SANTO TOME Y PRINCIPE", "SANTO TOME"),
    GameUIState("SENEGAL", "DAKAR"),
    GameUIState("SEYCHELLES", "VICTORIA"),
    GameUIState("SIERRA LEONA", "FREETOWN"),
    GameUIState("SOMALIA", "MOGADISCIO"),
    GameUIState("SUDAFRICA", "PRETORIA"),
    GameUIState("SUDAN", "JARTUM"),
    GameUIState("SUDAN DEL SUR", "YUBA"),
    GameUIState("SUAZILANDIA", "LOBAMBA"),
    GameUIState("TANZANIA", "DAR EL SALAM"),
    GameUIState("TUNEZ", "TUNEZ"),
    GameUIState("TOGO", "LOME"),
    GameUIState("UGANDA", "KAMPALA"),
    GameUIState("YIBUTI", "YIBUTI"),
    GameUIState("ZAMBIA", "LUSAKA"),
    GameUIState("ZIMBABUE", "HARE")
)
var paisesAfrReversed: MutableList<GameUIState> = mutableListOf(
    GameUIState("LUANDA", "ANGOLA"),
    GameUIState("ARGEL", "ARGELIA"),
    GameUIState("PORTO NOVO", "BENIN"),
    GameUIState("GABORONE", "BOTSUANA"),
    GameUIState("UAGADUGU", "BURKINA FASO"),
    GameUIState("BUYUMBURA", "BURUNDI"),
    GameUIState("PRAIA", "CABO VERDE"),
    GameUIState("YAUNDE", "CAMERUN"),
    GameUIState("BANGUI", "REPUBLICA CENTROAFRICANA"),
    GameUIState("MORONI", "COMORES"),
    GameUIState("YAMUSUKRO", "COSTA DE MARFIL"),
    GameUIState("YAMENA", "CHAD"),
    GameUIState("EL CAIRO", "EGIPTO"),
    GameUIState("ASMARA", "ERITREA"),
    GameUIState("ADDIS ABEBA", "ETIOPIA"),
    GameUIState("LIBRE VILLE", "GABON"),
    GameUIState("BANJUL", "GAMBIA"),
    GameUIState("ACCRA", "GHANA"),
    GameUIState("CONAKRY", "GUINEA CONAKRY"),
    GameUIState("BISSAU", "GUINEA BISSAU"),
    GameUIState("MALABO", "GUINEA ECUATORIAL"),
    GameUIState("NAIROBI", "KENIA"),
    GameUIState("MASERU", "LESOTO"),
    GameUIState("MONROVIA", "LIBERIA"),
    GameUIState("TRIPOLI", "LIBIA"),
    GameUIState("ANTANANARIVO", "MADAGASCAR"),
    GameUIState("LILONGUE", "MALAUI"),
    GameUIState("BAMAKO", "MALI"),
    GameUIState("RABAT", "MARRUECOS"),
    GameUIState("PORT LOUIS", "MAURICIO"),
    GameUIState("NUAKCHOT", "MAURITANIA"),
    GameUIState("MAPUTO", "MOZAMBIQUE"),
    GameUIState("WINDHOEK", "NAMIBIA"),
    GameUIState("NIAMEY", "NIGER"),
    GameUIState("ABUYA", "NIGERIA"),
    GameUIState("KIGALI", "RUANDA"),
    GameUIState("BRAZZAVILLE", "REPUBLICA DEL CONGO"),
    GameUIState("KINSHASA", "REPUBLICA DEMOCRATICA DEL CONGO"),
    GameUIState("SANTO TOME", "SANTO TOME Y PRINCIPE"),
    GameUIState("DAKAR", "SENEGAL"),
    GameUIState("VICTORIA", "SEYCHELLES"),
    GameUIState("FREETOWN", "SIERRA LEONA"),
    GameUIState("MOGADISCIO", "SOMALIA"),
    GameUIState("PRETORIA", "SUDAFRICA"),
    GameUIState("JARTUM", "SUDAN"),
    GameUIState("YUBA", "SUDAN DEL SUR"),
    GameUIState("LOBAMBA", "SUAZILANDIA"),
    GameUIState("DAR EL SALAM", "TANZANIA"),
    GameUIState("TUNEZ", "TUNEZ"),
    GameUIState("LOME", "TOGO"),
    GameUIState("KAMPALA", "UGANDA"),
    GameUIState("YIBUTI", "YIBUTI"),
    GameUIState("LUSAKA", "ZAMBIA"),
    GameUIState("HARE", "ZIMBABUE")
)

var paisesEuAleatorios = paisesEu.toList().shuffled()
var paisesEuReversedAleatorios = paisesEuReversed.toList().shuffled()
var paisesTodosAleatorios = paisesTodos.toList().shuffled()
var paisesTodosReversedAleatorios = paisesTodosReversed.toList().shuffled()
var paisesOceaniaAleatorios = paisesOceania.toList().shuffled()
var paisesOceaniaReversedAleatorios = paisesOceaniaReversed.toList().shuffled()
var paisesAsiaAleatorios = paisesAsia.toList().shuffled()
var paisesAsiaReversedAleatorios = paisesAsiaReversed.toList().shuffled()
var paisesAmAleatorios = paisesAm.toList().shuffled()
var paisesAmReversedAleatorios = paisesAmReversed.toList().shuffled()
var paisesAfrAleatorios = paisesAfr.toList().shuffled()
var paisesAfrReversedAleatorios = paisesAfrReversed.toList().shuffled()


fun iterarRespuesta(lista: List<GameUIState>, iterador: Int): String {
    return lista[iterador].respuesta
}

fun iterarPregunta(lista: List<GameUIState>, iterador: Int): String {
    return lista[iterador].pregunta
}

fun calcularFallos(estado: MutableList<GameUIState>): Int {
    return (estado.size / 3).toInt()
}
